[Log]
Level = 'debug'

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '31337'  # Hardhat
FinalityDepth = 1

[[EVM.Nodes]]
Name = 'Hardhat'
WSURL = 'ws://host.docker.internal:8545'
HTTPURL = 'http://host.docker.internal:8545'
